package by.psrer.entity.enums;

public enum UserState {
    BASIC,
    ROUTE_SELECTION,
    QUESTION_SELECTION,
    QUESTION,
    QUESTION_ANSWER,
    DELETE_QUESTION,
    ROUTE,
    ROUTE_DESCRIPTION,
    ROUTE_IMAGE_NAME,
    ROUTE_IMAGE_URL,
    DELETE_ROUTE
}